In [1]:
# Helps to choose how many convoltion , flatten, dense layers to use 
!pip install keras-tuner

     |████████████████████████████████| 98 kB 3.7 MB/s 


In [3]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [4]:
print(tf.__version__)

2.7.0


In [5]:
# Dataset  - fashion MNIST
fashion_mnist = keras.datasets.fashion_mnist

In [8]:
(train_images, train_labels),(test_images, test_labels) = fashion_mnist.load_data()

4431872/4422102 [==============================] - 0s 0us/step


In [9]:
train_images  #all grey scale pictures

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [10]:
# Scaling to 0 to 1  from 0-255

train_images = train_images/255.0
test_images = test_images/255.0

In [11]:
train_images[0].shape  #28X28 pixels

(28, 28)

In [12]:
train_images = train_images.reshape(len(train_images),28,28,1)

In [13]:
train_images

array([[[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
 

In [14]:
#Helps in how many layers to rake
test_images = test_images.reshape(len(test_images),28,28,1)  #28x28n pixels and b7w has 1 channel

In [15]:
test_images

array([[[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
 

In [16]:
len(train_images)

60000

In [32]:
# https://keras.io/keras_tuner/


def buildmodel(hp):
  model = keras.Sequential(
      [
       #input layer
       keras.layers.Conv2D(
           filters = hp.Int('conv_1_filter', min_value=32,max_value=128, step=16),
           kernel_size = hp.Choice('conv_1_kernel', values=[3,5]), #filter size
           activation ='relu',
           input_shape=(28,28,1) 
       ),
       keras.layers.Conv2D(
           filters = hp.Int('conv_1_filter', min_value=32,max_value=128, step=16),
           #filter size
           kernel_size = hp.Choice('conv_1_kernel', values=[3,5]),
           activation ='relu', 
       ),
       keras.layers.Flatten(),
       keras.layers.Dense(
           units = hp.Int('dense_1_units',min_value=32,max_value=128, step=16),
           activation='relu'
       ),
       keras.layers.Dense(10,activation='softmax')  #output layer
      ]
  ) 

  model.compile(optimizer=keras.optimizers.Adam(hp.Choice('learning_rate',values=[1e-2,1e-3])),
                loss='sparse_categorical_crossentropy', #for classification problem
                metrics=['accuracy'])
  
  return model



In [33]:
# Hyperparameter tuning

from kerastuner import RandomSearch
from kerastuner.engine.hyperparameters import HyperParameters

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: `import kerastuner` is deprecated, please use `import keras_tuner`.
  This is separate from the ipykernel package so we can avoid doing imports until


In [34]:

tuner_search = RandomSearch(buildmodel, objective='val_accuracy',max_trials=5,directory='output',project_name='Mnist Fashion') #  5 trails and tells the best value

In [35]:
#by default 2 epochs
tuner_search.search(train_images, train_labels,epochs=3, validation_split=0.1)

Trial 5 Complete [00h 00m 49s]
val_accuracy: 0.9200000166893005

Best val_accuracy So Far: 0.9200000166893005
Total elapsed time: 00h 06m 15s
INFO:tensorflow:Oracle triggered exit


In [36]:
model = tuner_search.get_best_models(num_models=1)[0]

In [38]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 64)        640       
                                                                 
 conv2d_1 (Conv2D)           (None, 24, 24, 64)        36928     
                                                                 
 flatten (Flatten)           (None, 36864)             0         
                                                                 
 dense (Dense)               (None, 64)                2359360   
                                                                 
 dense_1 (Dense)             (None, 10)                650       
                                                                 
Total params: 2,397,578
Trainable params: 2,397,578
Non-trainable params: 0
_________________________________________________________________


In [39]:
#already 3 epochs is trained above so start from 3rd epoch

model.fit(train_images, train_labels, epochs=10, validation_split=0.1, initial_epoch=3)



Epoch 4/10
1688/1688 [==============================] - 18s 10ms/step - loss: 0.1230 - accuracy: 0.9540 - val_loss: 0.2776 - val_accuracy: 0.9103
Epoch 5/10
1688/1688 [==============================] - 16s 10ms/step - loss: 0.0849 - accuracy: 0.9692 - val_loss: 0.2855 - val_accuracy: 0.9152
Epoch 6/10
1688/1688 [==============================] - 16s 9ms/step - loss: 0.0594 - accuracy: 0.9786 - val_loss: 0.3399 - val_accuracy: 0.9143
Epoch 7/10
1688/1688 [==============================] - 16s 9ms/step - loss: 0.0409 - accuracy: 0.9857 - val_loss: 0.3892 - val_accuracy: 0.9160
Epoch 8/10
1688/1688 [==============================] - 16s 10ms/step - loss: 0.0329 - accuracy: 0.9885 - val_loss: 0.4139 - val_accuracy: 0.9128
Epoch 9/10
1688/1688 [==============================] - 16s 9ms/step - loss: 0.0278 - accuracy: 0.9905 - val_loss: 0.4818 - val_accuracy: 0.9152
Epoch 10/10
1688/1688 [==============================] - 15s 9ms/step - loss: 0.0202 - accuracy: 0.9930 - val_loss: 0.5267 - va